apiVersion: apps/v1
kind: Deployment
metadata:
    name: rentora-frontend
    namespace: rentora
spec:
    replicas: 3
    selector:
        matchLabels:
            app: rentora-frontend
    strategy:
      type: RollingUpdate
      rollingUpdate:
        maxUnavailable: 1
        maxSurge: 1
    template:
        metadata:
            labels:
                app: rentora-frontend
        spec:
            containers:
            - name: frontend
              image: midnight4002/rentora_frontend:latest
              ports: 
                - containerPort: 5173
---
apiVersion: v1
kind: Service
metadata:
  name: rentora-frontend-service
  namespace: rentora
spec:
  selector:
    app: rentora-frontend
  ports:
    - name: http
      port: 80
      targetPort: 5173
  type: LoadBalancer
