apiVersion: apps/v1
kind: Deployment
metadata:
  name: rentora-frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: rentora-frontend
  template:
    metadata:
      labels:
        app: rentora-frontend
    spec:
      containers:
      - name: rentora-frontend
        image: chanathipcha24/rentora-interface:latest
        ports:
        - containerPort: 80
        env:
        - name: RENTORA_API_BASE_URL
          value: "http://localhost:30081" # use backend service
---
apiVersion: v1
kind: Service
metadata:
  name: rentora-frontend-service
spec:
  selector:
    app: rentora-frontend
  ports:
    - port: 80
      targetPort: 80
  type: LoadBalancer